name: freeland
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  extended_image: ^6.0.1
  flutter_countdown_timer: ^4.1.0
  confetti: ^0.6.0
  flutter_zoom_drawer: ^3.0.1
  flutter_staggered_animations: ^1.0.0
  provider: ^6.0.2
  timeline_tile: ^2.0.0
  flutter_slider_drawer: ^2.1.1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.0
  flutter_svg_provider: ^1.0.3
  bottom_navy_bar: ^6.0.0
  dio: ^4.0.4
  carousel_slider: ^4.1.1
  url_launcher: ^6.0.17
  bot_toast: ^4.0.1
  catcher: ^0.6.9
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  go_router: ^3.0.4
  device_preview: ^1.0.0
  cached_network_image: ^3.2.0
  get_it: ^7.2.0
  permission_handler: ^8.3.0
  internet_connection_checker: ^0.0.1+3
  flutter_local_notifications: ^9.2.0
  logging: ^1.0.2
  slidy: any
  either_dart: ^0.1.4
  drift: ^1.4.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  lottie: ^1.2.2
  badges: ^2.0.2
  dio_flutter_transformer2: ^4.0.1
  hive: ^2.1.0
  reactive_forms: ^11.0.0
  flutter_screenutil: ^5.5.3+2
  intl: ^0.17.0
  reactive_dropdown_search: ^0.6.0
  reactive_date_time_picker: ^0.2.0
  font_awesome_flutter: ^10.1.0
  colours: ^0.0.2
  readmore: ^2.1.0
  comment_box: ^0.0.17
  syncfusion_flutter_sliders: ^20.2.39
  smooth_page_indicator: ^1.0.0+2
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3
  flutter_image_compress: ^1.1.1
  image_cropper: ^3.0.0
  internet_file: any
  native_pdf_view: ^6.0.0+1
  fancy_dialog: ^1.0.1
  timeago: ^3.2.2
  myfatoorah_flutter: ^2.1.12
  pull_to_refresh: ^2.0.0


  dio_refresh_bot:
    git:
      url: https://github.com/flutterbots/flutterbots.git
      ref: fix_refresh_token
      path: packages/dio_refresh_bot


dependency_overrides:
  image_picker_android: ^0.8.5+2


dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3
  freezed: ^1.1.1
  change_app_package_name: ^1.0.0
  dart_code_metrics: ^4.10.1
  drift_dev: ^1.4.0




flutter:

  uses-material-design: true
  assets:

    - assets/images/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai_Bold.ttf
        - asset: assets/fonts/Almarai_Light.ttf
        - asset: assets/fonts/Almarai_ExtraBold.ttf
        - asset: assets/fonts/Almarai_Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#  flutter pub run easy_localization:generate -O lib/localization -S translations  -f keys -o locale_keys.g.dart
#  flutter pub run easy_localization:generate -O lib/localizations -S translations -f json
